# Generated by Django 3.1.7 on 2021-06-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dastavkaitem',
            name='cook',
        ),
        migrations.RemoveField(
            model_name='dastavkaitem',
            name='dastavka',
        ),
        migrations.RemoveField(
            model_name='dastavkaitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Dastavka',
        ),
        migrations.DeleteModel(
            name='DastavkaItem',
        ),
    ]
